/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;
public enum Color implements TEnum{
    RED(1),
    YELLOW(2),
    GREEN(3),
    BLUE(4);

  private static final Map<Integer, Color> BY_VALUE = new HashMap<Integer,Color>() {{
    for(Color val : Color.values()) {
      put(val.getValue(), val);
    }
  }};

  private final int value;

  private Color(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Color findByValue(int value) { 
    return BY_VALUE.get(value);
  }
}
